spring:
  application:
    name: consumer



rpc:
  client:
    type: nacos
    balance: fullRoundBalance
    discovery-addr: 127.0.0.1:8848

server:
  port: 9092

logging:
  level:
    root: debug
    org.springframework.web: debug
    com.winterchen: debug
